apiVersion: v1
kind: Service
metadata:
  name: {{ include "beloved.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: beloved
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: beloved
